name: learn-github-actions
on: workflow_dispatch
jobs:
  sanity-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: node -v
      - run: npm ci
      - run: npm run sanity-check
      - run: npm run test
