name: learn-github-actions
on: [push]
jobs:
    sanity-check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                node-version: '14'
            - run: npm install yarn
            - run: node -v
            - run: yarn -v
            - run: yarn install
            - run: yarn sanity-check