name: learn-github-actions
on: [push]
jobs:
    check-tech-versions:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
            - run: npm install yarn
            - run: node -v
            - run: yarn -v
            - run: npm -v